# Generated by Django 3.0.4 on 2020-03-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200304_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='dummy-shirt', max_length=100),
            preserve_default=False,
        ),
    ]
