# Generated by Django 3.0.4 on 2020-03-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200307_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billig_address',
            new_name='billing_address',
        ),
    ]
