# Generated by Django 3.0.4 on 2020-03-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_payment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
