# Generated by Django 3.0.4 on 2020-03-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200309_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='products-images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='products-images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to='products-images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products-images'),
        ),
    ]
