# Generated by Django 3.0.4 on 2020-03-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200309_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.ImageField(blank=True, null=True, upload_to='banner_images')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='banner_images')),
                ('third_image', models.ImageField(blank=True, null=True, upload_to='banner_images')),
            ],
        ),
    ]
