# Generated by Django 3.0.4 on 2020-03-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200309_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='banners',
        ),
        migrations.AddField(
            model_name='item',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images'),
        ),
    ]
